FFGames.Web/FFGames.Web/Models/Session/GameVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FFGames.Web.Models.Session
{
    public class GameVM
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int PlayerCount { get; set; }

        public int TeamSize { get; set; }

        public int TeamAmount { get; set; }

        public int TeamCount { get; set; }

        public bool UserIsInGame { get; set; }

        public bool HasTournament { get; set; }

        public bool TournamentHasStarted { get; set; }
    }
}

FFGames.Web/FFGames.Web/Models/Session/SessionVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FFGames.Web.Models.Session
{
    public class SessionVM
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public IEnumerable<GameVM> Games { get; set; }

        public IEnumerable<string> Users { get; set; }
    }
}

FFGames.Web/FFGames.Web/Controllers/SessionController.cs
using FFGames.Data;
using FFGames.Data.Models;
using FFGames.Web.Helpers;
using FFGames.Web.Models.Session;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FFGames.Web.Controllers
{
    public class SessionController : BaseController
    {
        public ActionResult CreateSession()
        {
            return View(new SessionVM());
        }

        [HttpPost]
        public ActionResult SaveSession(SessionVM vm)
        {
            using(var context = new GameContext())
            {
                var session = new Session
                {
                    Name = vm.Name,
                    CreatedBy = UserHelper.GetCurrentUser().Id,
                    DateCreated = DateTime.Now
                };

                context.Sessions.Add(session);
                context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult Session(int id)
        {
            using(var context = new GameContext())
            {
                var session = context.Sessions.SingleOrDefault(s => s.Id == id);

                if (session == null)
                    return HttpNotFound();

                var model = new SessionVM
                {
                    Id = session.Id,
                    Name = session.Name,
                    Games = session.GameSessions.Select(g => new GameVM
                    {
                        Id = g.Id,
                        Name = g.Name,
                        PlayerCount = g.Users.Count,
                        TeamCount = g.Teams.Count,
                        TeamSize = g.TeamSize,
                        UserIsInGame = g.Users.Contains(UserHelper.GetCurrentDbUser(context)),
                        HasTournament = false,
                        TournamentHasStarted = false
                    }).ToList(),
                    Users = session.Users.Select(u => u.UserName)
                };

                return View(model);
            }
        }

        public ActionResult EnterSession(int id)
        {
            using (var context = new GameContext())
            {
                var session = context.Sessions.SingleOrDefault(s => s.Id == id);

                if (session == null)
                    return HttpNotFound();

                session.Users.Add(UserHelper.GetCurrentDbUser(context));
                context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult LeaveSession(int id)
        {
            using (var context = new GameContext())
            {
                var session = context.Sessions.SingleOrDefault(s => s.Id == id);

                if (session == null)
                    return HttpNotFound();

                session.Users.Remove(UserHelper.GetCurrentDbUser(context));
                context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
        }
    }
}

FFGames.Web/FFGames.Web/Views/Session/CreateSession.cshtml
@model FFGames.Web.Models.Session.SessionVM

@{
    ViewBag.Title = "CreateSession";
}

<h2>Create Session</h2>

@using (Html.BeginForm("SaveSession", "Session"))
{
    <div class="row">Name</div>
    <div class="row">@Html.EditorFor(m => m.Name)</div>
    <div class="row"><input type="submit" value="Create session" /></div>
}

FFGames.Web/FFGames.Web/Views/Session/Session.cshtml
@model FFGames.Web.Models.Session.SessionVM

@{
    ViewBag.Title = "Session";
}

<div class="row">
    <h2>@Model.Name</h2>
</div>

<div class="row">
    <div class="col-lg-5">
        <div class="row"><strong>Participants</strong></div>
        @foreach (var user in Model.Users)
        {
            <div class="row">@user</div>
        }
    </div>
</div>
<div class="row">
    <div class="col-lg-2" style="padding-left: 0">
        <div id="add-game-button">Add game</div>
    </div>
</div>
<div class="row">
    @foreach(var game in Model.Games)
    {
        <div class="col-lg-2" style="padding-left: 0">
            <div class="panel panel-primary">
                <div id="panel-heading-@game.Id" class="panel-heading">@game.Name</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-8">Participants:</div>
                        <div class="col-lg-3">@game.PlayerCount</div>
                    </div>
                    <div class="row">
                        <div class="col-lg-8">Team size:</div>
                        <div class="col-lg-3">@game.TeamSize</div>
                    </div>
                    <div class="row">
                        <div class="col-lg-8">Teams:</div>
                        <div class="col-lg-3">@game.TeamCount</div>
                    </div>
                </div>
                @if (game.UserIsInGame)
                {
                    <a href="@Url.Action("LeaveGame", "Games", new { id = game.Id })"><div class="panel-heading panel-button panel-button-leave">Leave game</div></a>
                }
                else
                {
                    <a href="@Url.Action("EnterGame", "Games", new { id = game.Id })"><div class="panel-heading panel-button panel-button-enter">Enter game</div></a>
                }
            </div>
        </div>

        if (game.UserIsInGame)
        {
            <script>
                $('#panel-heading-@(game.Id)').click(function () {
                    window.location = '@Url.Action("Game", "Games", new { id = game.Id })';
                });
            </script>

            <style>
                #panel-heading-@(game.Id):hover {
                    cursor: pointer;
                    background-color: blue !important;
                }
            </style>
        }
    }
</div>

<script>
    $('#add-game-button').click(function () {
        window.location = '@Url.Action("AddGame", "Games", new { sessionId = Model.Id })';
    });
</script>

<style>
    #add-game-button {
        padding: 10px;
        color: white;
        background-color: dimgray;
        border-radius: 5px;
        cursor: pointer;
        margin-bottom: 10px;
    }

    #add-game-button:hover {
        background-color: gray;
    }

    .panel-button {
        border-radius: 3px;
        margin: 5px;
        color: white !important;
    }

        .panel-button:hover {
            cursor: pointer;
        }

    a:hover {
        text-decoration: none;
    }

    .panel-button-enter {
        background-color: green !important;
    }

        .panel-button-enter:hover {
            background-color: darkcyan !important;
        }

    .panel-button-leave {
        background-color: darkred !important;
    }

    .panel-button-leave:hover {
        background-color: orangered !important;
    }
</style>